services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1
    container_name: clickhouse_data_war_house
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./compose/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./compose/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8125:8123"


volumes:
  clickhouse_data:
  clickhouse_logs: